---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
      tier: frontend
  template:
    metadata:
      labels:
        app: flaskapp
        tier: frontend
    spec:
    containers:
      - name: app
        image: femmy1992/flaskapp:v1.0.0
        ports:
        - containerPort: 5500


--- 
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  type: LoadBalancer 
  selector:
    app: flaskapp
    tier: frontend
  ports:
  - port: 80
    targetPort: 5500
    nodePort: 30000
